### ISSUE TITLE
Lines with 'module' need to be commented out

### ISSUE THREAD

**Issue by halfychemist** [mpmeers/SEACR#1]
minor but consequential - the code did not run unless I commented out the following lines:
line 117 "module load R"
line 167 "module load bedtools"

Thanks for this great tool!

**Comment by mpmeers** [comment]
Hi,

Thanks for the catch--we use centrally supported modules on our computing cluster, and so those calls are specific to that scenario and would be extraneous when running from a personal computer. I will comment those lines out in the master version.

Mike

**Comment by halfychemist** [comment]
Hi Mike, thanks for the clarification! That sounds like a valuable
consideration in case we choose to also run on our central cluster in the
future. For me it's all new and nothing is obvious right now, so I do
appreciate the clarification.
Yours,
Liane
