### ISSUE TITLE
integrating seacr in conda

### ISSUE THREAD

**Issue by yeroslaviz** [mpmeers/SEACR#30]
Are you planning to integrate this amazing tool in the conda environment?

**Comment by mpmeers** [comment]
Hi,

I don't currently have plans to integrate this with conda myself, but I'd certainly be open to working with others who are interested in making that happen. I can currently point you towards a web server ([https://seacr.fredhutch.org](https://seacr.fredhutch.org)) and development of a Galaxy wrapper (Issue #29) for alternative ways to use SEACR. Thanks for your interest.

Mike

**Comment by stephanflemming** [comment]
@yeroslaviz @mpmeers There is a bioconda recipe available here http://bioconda.github.io/recipes/seacr/README.html
