### ISSUE TITLE
Binary peak calls

### ISSUE THREAD

**Issue by jzohren** [mpmeers/SEACR#37]
Hello,

I tried to analyse my data with SEACR and managed to produce output in the end. However, the resulting file only contains "binary" peak calls, i.e. all values are 1. This is what I did:

- mapping with bowtie2 (parameters as suggested in paper):
```bash
bowtie2 --local --very-sensitive-local --no-unal --no-mixed --no-discordant --phred33 -I 10 -X 700 -p 16 -x $GENOME -1 $READ1 -2 $READ2 -S $OUTPUT
```
- converting BAM to BDG (as explained in readme): 
```bash
samtools sort -n $INPUT | samtools view -bf 0x2 -F 0x800 - | bedtools bamtobed -bedpe -i stdin > $OUTNAME.bed
awk '$1==$4 && $6-$2 < 1000 {print $0}' $OUTNAME.bed > $OUTNAME.clean.bed
cut -f 1,2,6 $OUTNAME.clean.bed | sort -k1,1 -k2,2n -k3,3n > $OUTNAME.fragments.bed
bedtools genomecov -bg -i $OUTNAME.fragments.bed -g $SIZES > $OUTNAME.fragments.bedgraph
```
- running SEACR:
```bash
bash SEACR_1.3.sh $INPUT 0.01 non stringent $OUTPUT
```
- converting BED to bedgraph:
```bash
bedtools genomecov -bg -i $OUTPUT.bed -g $SIZES > $OUTPUT.bdg
```

The input bedgraph to SEACR looks like this:

> chr1    3000617 3001227 5
> chr1    3001788 3001835 1
> chr1    3001920 3001974 1
> chr1    3005481 3005846 11
> chr1    3007565 3007786 6

And the output BED file like this:

> chr1    4476880 4485272 318405  108     chr1:4482277-4482328
> chr1    4494350 4505162 327365  72      chr1:4495401-4495740
> chr1    4676901 4690615 404399  82      chr1:4679499-4689402
> chr1    5004148 5016900 426418  116     chr1:5010029-5010069
> chr1    9605337 9615014 317997  110     chr1:9606718-9606732

And finally the bedgraph file:

> chr1    4476880 4485272 1
> chr1    4494350 4505162 1
> chr1    4676901 4690615 1
> chr1    5004148 5016900 1
> chr1    9605337 9615014 1
> chr1    9630384 9645946 1

I'm using Bowtie2 v2.3, samtools v1.3, and bedtools v2.27.

Any suggestions of what's going on would be highly appreciated! Thanks in advance and best wishes.

Jasmin

**Comment by mpmeers** [comment]
Hi Jasmin,

It actually appears that SEACR functioned as expected--the output BED file is the final output from SEACR, and converting that file to a bedgraph is not necessary. In fact, if you do that you expect to have a "binary" bedgraph since the SEACR peak calls are all non-overlapping, so the resulting bedgraph just ends up being a glorified BED file. Hope that helps.

Mike

**Comment by jzohren** [comment]
Hi Mike,

Thanks for getting back to me so quickly and sorry that I had misunderstood the way SEACR was supposed to function. I'm fairly new to the peak-calling world and am still exploring available tools.

Jasmin
