### ISSUE TITLE
Long pending time when using SEACR

### ISSUE THREAD

**Issue by ahua217** [mpmeers/SEACR#45]
Hello mpeers and everyone, I found my webpage use of SEACR seems to be stuck at pending stage now. I also tried the files successfully running with SEACR webpage before, and their pending time is also endless. Any clue?

Thank you very much!

**Comment by mpmeers** [comment]
Hi,

This is an issue that has cropped up with the web page in the past--tagging @dtenenba to take a look. Also note that there is a "Report Issue" tab at the top of the SEACR web server page for issues specifically related to the web server.  Hopefully we can get it resolved soon.

Mike

**Comment by dtenenba** [comment]
Thanks for reporting this issue. It has been resolved.

**Comment by ahua217** [comment]
Thank you so much dtenenba and Mike!

**Comment by ahua217** [comment]
@dtenenba, it ran well during the morning but now it returns error even if the input file is that one tested good before. So I guess it is due to the same reason as that of the blockage at pending status. I already submitted the condition through "report issue". Thanks!

**Comment by dtenenba** [comment]
Hmmmm..... I am not seeing any problems now. It works for me using test files from @mpmeers .
I will send you an email and maybe you can provide your files via google drive or dropbox or some other method.
