### ISSUE TITLE
WARNING seqname is marked as paired, but its mate does not occur next to it in your BAM file. Skipping

### ISSUE THREAD

**Issue by kdbchau** [mpmeers/SEACR#51]
Hi, 

I am trying to end up with a fastq file of all mapped paired reads and a fastq file of all unmapped reads. But towards the end of my pipeline I am getting thousands of the warning "seq is marked as paired, but its mate does not occur next it in your BAM file. Skipping". Because it spams my terminal so much I can't tell if its an issue with my unmapped or mapped bam file. 

here is my pipeline:

    bwa index refgenome.fa
    bwa mem -B 2 -M refgenome.fa cert1.R1.fastq cert1.R2.fastq > cert1_aln.sam
    samtools view -Sb cert1_aln.sam > cert1_aln.bam
    
    # I do a sort here but maybe I don't need to? I have just seen many pipelines that sort and index at this point so I did it too.
    samtools sort cert1_aln.bam > cert1_aln_sorted.bam | rm -f cert1_aln.bam
    samtools index cert1_aln_sorted.bam
    
    # Gather some stats
    samtools flagstat cert1_aln_sorted.bam > cert1_stats.txt
    
    # Extract unmapped read whose mate is mapped
    samtools view -b -f 4 -F 264 cert1_aln_sorted.bam > cert1_tmp1_unmapped.bam
    # Extract mapped read whose mate is unmapped
    samtools view -b -f 8 -F 260 cert1_aln_sorted.bam > cert1_tmp2_unmapped.bam
    # Extract unmapped read with unmapped mate
    samtools view -b -f 12 -F 256 cert1_aln_sorted.bam > cert1_tmp3_unmapped.bam
    
    # Merge the three tmp files into 1
    samtools merge cert1_unmapped.bam cert1_tmp*_unmapped.bam
    
    # Extract mapped reads from BAM file
    samtools view -b -F 12 cert1_aln_sorted.bam > cert1_mapped.bam
    
    # Sort the BAM files by name
    samtools sort -n cert1_unmapped.bam > cert1_unmapped_sorted.bam
    samtools sort -n cert1_mapped.bam > cert1_mapped_sorted.bam
    
    # Finally, convert to Fastq
    bamToFastq -i cert1_unmapped_sorted.bam -fq cert1_unmapped.R1.fastq -fq2 cert1_unmapped.R2.fastq
    bamToFastq -i cert1_mapped_sorted.bam -fq cert1_mapped.R1.fastq -fq2 cert1_mapped.R2.fastq

Is it because I am doing an initial sort to get my cert_aln_sorted.bam file? I am following other protocols which always have a sort and index and after creating the bam file, and I figured I am sorting the mapped and unmapped bam files anyways by name so what is the issue here? Why is it unable to just convert the file to fastq. My stats files show that about 98% of the reads are proper paired reads but I do see a discrepancy when using samtools flagstat and bamtools stats:

# BAMTOOLS STATS
Total reads:       25730940
Mapped reads:      25300974	(98.329%)
Forward strand:    13080593	(50.8361%)
Reverse strand:    12650347	(49.164%)
Failed QC:         0	(0%)
Duplicates:        0	(0%)
Paired-end reads:  25730940	(100%)
'Proper-pairs':    24074026	(93.5606%)
Both pairs mapped: 25294100	(98.3023%)
Read 1:            12867458
Read 2:            12863482
Singletons:        6874	(0.0267149%)
Average insert size (absolute value): 815.247
Median insert size (absolute value): 229

# SAMTOOLS FLAGSTAT
25730940 + 0 in total (QC-passed reads + QC-failed reads)
111474 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
25300974 + 0 mapped (98.33% : N/A)
25619466 + 0 paired in sequencing
12809733 + 0 read1
12809733 + 0 read2
24045298 + 0 properly paired (93.86% : N/A)
25182938 + 0 with itself and mate mapped
6562 + 0 singletons (0.03% : N/A)
1071166 + 0 with mate mapped to a different chr
297377 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by mpmeers** [comment]
Hi,

I'm going to close this issue since it's not specifically related to SEACR, but it sounds like you need to sort your BAMs by name rather than position. A user from issue #26 ran into a similar error.

Mike

**Comment by kdbchau** [comment]
Hey! Yea no worries I tried to remove this post realizing I posted in the wrong forum (oops). But it was not an issue with samtools sort. It was with bamToFastq just not being able to handle reads that had a mate mapped or not. Using samtools builtin bam to fastq conversion worked.
