### ISSUE TITLE
SEACR Error when Running Locally

### ISSUE THREAD

**Issue by jjp55** [mpmeers/SEACR#57]
Hello, 

I am trying to run SEACR locally using the command:

bash SEACR_1.3.sh target.bedgraph Control.bedgraph norm stringent sample1

When I run this, it can get to the "Calculating threshold using normalized control," but then I receive this error. 

dyld: Library not loaded: @rpath/./libreadline.6.2.dylib
  Referenced from: /Users//opt/anaconda3/lib/R/lib/libR.dylib
  Reason: image not found

**Comment by jjp55** [comment]
Further, when I try to run the same samples on the web interface, it seems to get stuck and stalls at: 
"Creating experimental AUC file"

**Comment by mpmeers** [comment]
Hi,

Apologies for the delay in responding. This output is at the point where an R script is invoked, so is it possible that you have an incorrect installation of/path to R on your machine? The second line of your error suggests this may be the case.

Mike
