### ISSUE TITLE
Error when no peaks are found : awk: cmd. line:1: fatal: division by zero attempted

### ISSUE THREAD

**Issue by Adrien-Evo** [mpmeers/SEACR#62]
Hi, 
I have a painful error when using seacr on some very noisy samples. My temp files pDs3137ShHtfZ.auc.threshold.bed is of lengfth 0, so no regions have been deemed as a peak. Then I have this awk error:

 awk: cmd. line:1: fatal: division by zero attempted

I assume you try to divide something by the number of peaks, that in my case is 0.

Could you try to catch this error or check if there is no peak before launching awk and just display a message on stdout ? 
I'm trying to use seacr in pipeline and having  to verify if an error is due to genuine bugs or just a bad sample is always a pain :)

I'll maybe propose a pull request.
Thank you

**Comment by mpmeers** [comment]
Hi,

Apologies for the delay in responding here, and thanks for bringing this to my attention--I agree this is probably the result of a divide-by-count issue (I'm guessing at line 165 in SEACR_1.3.sh, though I can't be sure without access to the same data to replicate the error), and I also agree that this is not good code etiquette :-) I've added what I hope might be a fix to a new test branch ([mpmeers-patch-210627](https://github.com/FredHutch/SEACR/tree/mpmeers-patch-210627)) in which I now have a loop to circumnavigate that line if the temporary file output is empty. Would you mind testing this out to see if it fixes the issue? Alternatively I'm happy to take a look at a pull request if you have a more elegant solution in mind.

Mike

**Comment by Adrien-Evo** [comment]
Hi,
Your fix is great. I tried it and it worked well with my bad quality file.  There's just a missing parenthesis in the R file that I'll suggest a pull. Your is good imo.
