### ISSUE TITLE
line 102: p?wfYqtQKC??l.auc.bed: Invalid argument

### ISSUE THREAD

**Issue by jjp55** [mpmeers/SEACR#68]
Hello, 

I recently tried to run SEACR. For it, I created a new conda environment and installed it using conda. 
When I tried to run the code:

bash SEACR_1.3.sh Target-1_chr.bedgraph IgG-1_chr.bedgraph norm stringent Output-SEARC

I got the following error:
Calling enriched regions with control file
Normalizing control to experimental bedgraph
Using stringent threshold
Creating experimental AUC file: Thu Aug 19 14:18:29 EDT 2021
/Users/jordanpowers/opt/anaconda3/envs/SEACR/bin/SEACR_1.3.sh: line 102: p?wfYqtQKC??l.auc.bed: Invalid argument

Do you have any suggestions on how to troubleshoot this? Thank you!

**Comment by mpmeers** [comment]
Hi,

I think this is related to a problem that was brought up in issue #54 in which there's an OS-dependent bug in the pseudorandom string assignment by /dev/urandom. I've updated [v1.4](https://github.com/FredHutch/SEACR/tree/v1.4-beta.2) with a fix to this, so maybe you could give that a try to see if it works for you.

Mike

**Comment by jjp55** [comment]
Hi Mike, 

Thank you for the suggestion! It seems to be working now. 

Best,

Jordan

**Comment by mpmeers** [comment]
Hi Jordan,

Glad that worked--if you want to remain consistent with v1.3 you can also just replace lines 56-57 in SEACR_1.3.sh:

``password=`head /dev/urandom | LC_CTYPE=C tr -dc A-Za-z0-9 | head -c 13; echo ''` ``
``password2=`head /dev/urandom | LC_CTYPE=C tr -dc A-Za-z0-9 | head -c 13; echo ''` ``


with the following:

``password=`head /dev/urandom | base64 | tr -d '/+-=' | head -c 13; echo ''` ``
``password2=`head /dev/urandom | base64 | tr -d '/+-=' | head -c 13; echo ''` ``

Closing this for now.

Mike
