### ISSUE TITLE
Multiple input files

### ISSUE THREAD

**Issue by prmunn** [mpmeers/SEACR#77]
I'm looking for a way to call peaks on multiple bedgraph files simultaneously, similar to the way macs2 allows multiple BAM files after the -i option. Any suggestions on how I might di this?

**Comment by mpmeers** [comment]
Hi,

Unfortunately I haven't coded in that functionality at this time, but I will take it into consideration for the next update. In the meantime, in theory you could code a simple bash loop to feed a list of files to SEACR, maybe something along these lines if you're using [v1.4](https://github.com/FredHutch/SEACR/tree/SEACRv1.4_dev):

```
for i in `cat $1`
do
 j=`basename $i`
 bash SEACR_1.4.sh -b $i -c $2 -n norm -m stringent -o output_dir/$j
done
```

where your first input is a target file list and the second input is the control file. This assumes that the control file being used is the same for all target files, so just note that the code would have to be amended for multiple target-control file pairs. Hope that helps.

Mike

**Comment by prmunn** [comment]
Yes, that helps. Thank you.
