### ISSUE TITLE
SEACR web server not working

### ISSUE THREAD

**Issue by Lillianwu0314** [mpmeers/SEACR#78]
Hi,

I'm getting the pop-up error message "There has been a problem uploading your files". The web server used to work fine with the same input files.

Thanks,
Lillian

**Comment by mpmeers** [comment]
Hi Lillian,

My test files did hang up indefinitely when I tried to run them on the web server on Safari, but I wasn't able to replicate your specific error message (this could be browser-specific). We just rebooted the web server and it looks like it's running fine for me now, so can you give it another shot and let me know if it works? Thanks.

Mike

**Comment by Lillianwu0314** [comment]
Hi Mike,

It's working fine now, thanks for the fix!

Lillian
