### ISSUE TITLE
Error reading argsL$exp table

### ISSUE THREAD

**Issue by maddylee13** [mpmeers/SEACR#99]
When running the code, there is an issue with the SEACR_1.3.R script as it seems to be unable to read the argsL$exp table.

This is the error code that pops up:
Error in read.table(argsL$exp) : no lines available in input
Execution halted
Error in read.table(argsL$exp) : no lines available in input
Execution halted

**Comment by LucasMcNU** [comment]
I'm getting the same error. What was your solution for this?

**Comment by maddylee13** [comment]
How are you calling SEACR_1.3.sh? I believe I ended up uninstalling and reinstalling SEACR
